---
# Create a directory for the app
- name: Create a directory for the app
  become: true
  become_user: ec2-user
  file:
    path: "{{ app_dir}}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755

# Clone the repo
- name: Clone the repo
  become: true
  become_user: ec2-user
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_dir}}"
    force: yes

# Install app dependencies
- name: Install app dependencies
  become: true
  become_user: ec2-user
  shell: "npm install"
  args:
    chdir: "{{ app_dir}}"
    executable: /bin/bash
    creates: "{{ app_dir}}/node_modules"

# Start the app
- name: Start the app
  become: true
  become_user: ec2-user
  shell: "pm2 start app.js"
  args:
    chdir: "{{ app_dir}}"
    executable: /bin/bash

# Save the app configuration
- name: Save the app configuration
  become: true
  become_user: ec2-user
  shell: "pm2 save"
  args:
    chdir: "{{ app_dir}}"
    executable: /bin/bash